name: 🔐 Gitleaks Secret Scan + DefectDojo Upload

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - ready_for_review
      - reopened

  workflow_dispatch:

jobs:
  secret-scan:
    name: 🔐 Gitleaks + DefectDojo Upload
    runs-on: ubuntu-latest
    permissions: write-all

    # ✅ Skip the job if PR is closed and merged
    if: github.event.pull_request.state == 'open'

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Secret Scan & Upload
        uses: PoorneshORG/gitleaks-scan@baseline-action
        continue-on-error: false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dojo-url: ${{ secrets.DEFECTDOJO_URL }}
          dojo-api-key: ${{ secrets.DEFECTDOJO_API_KEY }}
          product-name: DevSecOps
          report-file: filtered-gitleaks-report.json
          repo-name: ${{ github.repository }}
          branch-name: ${{ github.head_ref || github.ref_name }}
